parameters: {}
environment: {}
packages:
  - name: webhooks
    functions:
      - name: health
        runtime: nodejs:18
        main: ''
        environment: {}
      - name: github
        runtime: nodejs:18
        main: ''
        environment: {}
        limits:
          timeout: 900000
