service: serverless-nestjs-api

provider:
  name: openfaas
  runtime: nodejs20.x
  stage: dev

functions:
  health-check:
    handler: dist/serverless.handler
    events:
      - http:
          path: /webhooks/health
          method: get