service: serverless-nestjs-api

provider:
  name: openfaas
  runtime: nodejs20.x
  stage: dev

functions:
  api:
    handler: dist/main.handler
    events:
      - http:
          path: /
          method: any
      - http:
          path: /{proxy+}
          method: any
