environment:
  # ENV is statically defined as "production" in this example:
  ENV: production
packages:
  - name: default
    environment:
      # DATABASE_URL will be substituted to the DATABASE_URL_READ_ONLY value
      # defined in App Platform's environment variable configuration.
      # NOTE: The receiving variable name does not need to match the name as
      # defined in the app / component config. This facilitates narrowly
      # scoped or overlapping values.
    functions:
      - name: webhooks/health
        environment:
